# Generated by Django 5.0.1 on 2024-01-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
        ('app_notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='notebook',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_notebooks.notebook'),
        ),
    ]
