# Generated by Django 5.0.1 on 2024-01-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_library_notebook'),
        ('app_notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='notebook',
        ),
        migrations.AddField(
            model_name='library',
            name='notebook_set',
            field=models.ManyToManyField(to='app_notebooks.notebook'),
        ),
    ]
