# Generated by Django 5.0.1 on 2024-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapters', models.IntegerField()),
                ('is_maths', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
