# Generated by Django 5.0.1 on 2024-01-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebooks', '0002_alter_notebook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
