# Generated by Django 5.0.1 on 2024-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebooks', '0003_notebook_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='image_relative_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
